# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('birthdate', models.CharField(max_length=100)),
            ],
        ),
    ]
