# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170719_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codetype', models.CharField(max_length=10)),
                ('codeid', models.CharField(max_length=10)),
                ('match', models.CharField(max_length=10)),
            ],
        ),
    ]
