# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='extradata1',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
    ]
